version: 0.0
os: linux
files:
 - source: /app
   destination: /home/ec2-user/rahul-web-app
 - source: requirements.txt
   destination: /home/ec2-user/rahul-web-app
permissions:
  - object: /home/ec2-user/rahul-web-app/app.py
    owner: ec2-user
    mode: 644
    type:
      - file
  - object: /home/ec2-user/rahul-web-app/run.py
    owner: ec2-user
    mode: 644
    type:
      - file
  - object: /home/ec2-user/rahul-web-app/requirements.txt
    owner: ec2-user
    mode: 644
    type:
      - file
  - object: /home/ec2-user/rahul-web-app/supervisor.conf
    owner: ec2-user
    mode: 644
    type:
      - file
hooks:
  AfterInstall:
   - location: scripts/install_dependencies
     timeout: 300
     runas: root
   - location: scripts/start_server
     timeout: 300
     runas: root